before_script:
  - apt-get update -q -y
  - apt-get install -y python3-dev python3-pip git
  - pip3 install pytest
  - git config --global http.sslverify "false"
  - pip3 install -r requirements.txt


test:
  script:
    - pytest