before_script:
  - apt-get update -q -y
  - wget https://www.tbi.univie.ac.at/RNA/download/ubuntu/ubuntu_18_04/viennarna_2.4.11-2_amd64.deb
  - dpkg -i viennarna_2.4.11-2_amd64.deb
  - apt-get install -f
  - apt-get install -y python3-dev python3-pip git
  - pip3 install pytest
  - git config --global http.sslverify "false"
  - pip3 install -e git+http://gitlab+deploy-token-2:kpZ6Fxu3nToyUaDJmgnw@git.lygos.com/design/d-tailor.git#egg=dtailor
  - pip3 install -r requirements.txt


test:
  script:
    - pytest